sudo: required
dist: trusty

language: node_js

node_js:
  - 6.2

addons:
  firefox: latest

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget http://www.slimjetbrowser.com/chrome/lnx/chrome64_53.0.2785.116.deb
 - sudo dpkg -i chrome*.deb

install:
  - npm install gulp --global
  - npm install codecov --global

before_script:
  - npm install

script:
  - gulp lint
  - gulp test-server
  - gulp test --browsers=PhantomJS
  - gulp test --browsers=Chrome
  - gulp test --browsers=Firefox

  - npm run dev-server &
  - ./e2e_test.sh

after_success:
  - codecov
