sudo: false

language: node_js

node_js:
  - "6.2"

before_script:
  - "npm install gulp --global"
  - "npm install"

script:
  - "gulp lint"
  - "npm run test"

after_success:
  - "cat artifacts/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
